In [4]:
import pandas as pd
import numpy as np

dfq = pd.read_csv("./survey_questions_meta.csv")

dfq.head()

,Q1-Volunteered For Animal welfare,Q1-Volunteered For Arts/Culture/Heritage,Q1-Volunteered For Children/Youth,Q1-Volunteered For Community building,Q1-Volunteered For Diversity & Inclusion,Q1-Volunteered For Environmental sustainability,Q1-Volunteered For Families,Q1-Volunteered For Health/Well-being (e.g mental health),Q1-Volunteered For Seniors,Q1-Volunteered For Poverty reduction,...,Q5-Stressed about Academic issues,Q5-Stressed about Financial issues,Q5-Stressed about Family issues,Q5-Stressed about Friendships,Q5-Stressed about Romantic relationships,Q5-Stressed about Health related issues,Q5-Stressed about Career related issues,"Q5-Stressed about My involvement in hostel, clubs, societies, interest groups, etc.",Q5-Stressed about Others,response_id
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Yes,No,No,No,No,No,No,No,No,1
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Yes,No,No,No,No,No,No,No,No,2
2,No,No,No,Yes,No,No,No,Yes,No,No,...,Yes,No,No,No,No,No,Yes,No,No,3
3,No,Yes,Yes,Yes,No,No,No,No,No,No,...,Yes,No,Yes,Yes,Yes,Yes,No,Yes,No,4
4,No,No,Yes,Yes,No,No,No,No,Yes,No,...,Yes,Yes,No,Yes,No,No,No,Yes,No,5

In [5]:
dfr = pd.read_csv("./survey_responses.csv")

dfr.head()

,Career,Citizenship,Nationality,Year since Matriculation,Year of Study,Primary Programme,Gender,Department,Housing Type,Q1-How many events have you Volunteered in ?,Q2-How many events have you Participated in ?,Q3-How many activities are you Interested in ?,Q4-How many activities are you Passionate about ?,Q5-What are your levels of stress ?,Q6-How Satisfied You are with your Student Life ?,Q7-How much effort do you make to interact with others ?,Q8-About How events are you aware about ?,response_id,Q9-What is an ideal student life ?
0,UGRD,Foreigner,Indonesia,2,2,Bachelor of Science,F,School of Science,Residences,0,1,3,1,1,2,2.0,2.0,1,NaN
1,UGRD,Country Citizen,Singapore,1,1,Bachelor of Engineering,F,School of Engineering,Out of Campus,0,1,2,3,1,2,2.0,3.0,2,Friends+CCas+good result
2,UGRD,Foreigner,Malaysia,2,2,Bachelor of Science,M,School of Science,Halls,3,1,1,5,2,2,2.0,2.0,3,just want everything to go smooth. serious
3,UGRD,Foreigner,Malaysia,2,2,Bachelor of Engineering,M,School of Engineering,Halls,3,4,3,3,7,1,1.0,1.0,4,NaN
4,UGRD,Foreigner,Viet Nam,3,3,Bachelor of Engineering,F,School of Engineering,Out of Campus,4,3,4,5,4,2,2.0,2.0,5,a mixture of both academic and non-academic

In [10]:
undergrads = dfr[dfr["Career"] == "UGRD"]

In [11]:
undergrads

,Career,Citizenship,Nationality,Year since Matriculation,Year of Study,Primary Programme,Gender,Department,Housing Type,Q1-How many events have you Volunteered in ?,Q2-How many events have you Participated in ?,Q3-How many activities are you Interested in ?,Q4-How many activities are you Passionate about ?,Q5-What are your levels of stress ?,Q6-How Satisfied You are with your Student Life ?,Q7-How much effort do you make to interact with others ?,Q8-About How events are you aware about ?,response_id,Q9-What is an ideal student life ?
0,UGRD,Foreigner,Indonesia,2,2,Bachelor of Science,F,School of Science,Residences,0,1,3,1,1,2,2.0,2.0,1,NaN
1,UGRD,Country Citizen,Singapore,1,1,Bachelor of Engineering,F,School of Engineering,Out of Campus,0,1,2,3,1,2,2.0,3.0,2,Friends+CCas+good result
2,UGRD,Foreigner,Malaysia,2,2,Bachelor of Science,M,School of Science,Halls,3,1,1,5,2,2,2.0,2.0,3,just want everything to go smooth. serious
3,UGRD,Foreigner,Malaysia,2,2,Bachelor of Engineering,M,School of Engineering,Halls,3,4,3,3,7,1,1.0,1.0,4,NaN
4,UGRD,Foreigner,Viet Nam,3,3,Bachelor of Engineering,F,School of Engineering,Out of Campus,4,3,4,5,4,2,2.0,2.0,5,a mixture of both academic and non-academic
5,UGRD,Country Citizen,Singapore,1,1,Bachelor of Science,F,School of Science,Residential Colleges,2,2,3,2,2,3,3.0,1.0,6,"One where Iâ€™m doing well academically, involve..."
6,UGRD,Country Citizen,Singapore,3,3,Bachelor of Business Admin,F,School of Business School,Out of Campus,1,2,4,3,3,2,2.0,2.0,7,NaN
7,UGRD,Foreigner,Indonesia,2,2,Bachelor of Computing,M,School of Computing,Halls,2,3,5,1,2,2,2.0,2.0,8,NaN
8,UGRD,Foreigner,Indonesia,3,3,Bachelor of Computing,M,School of Computing,Halls,0,2,3,1,5,2,1.0,2.0,9,My ideal student life will be one that spendin...
9,UGRD,Foreigner,Malaysia,2,2,Bachelor of Science,F,School of Science,Halls,2,1,3,2,5,2,2.0,1.0,10,"Good company around you, good grades, involvem..."
10,UGRD,Country Citizen,Singapore,2,2,Bachelor of Science,F,School of Science,Out of Campus,0,3,3,2,4,2,2.0,2.0,11,Maintain a well balance between academic and n...
11,UGRD,Foreigner,Malaysia,2,2,Bachelor of Science,M,School of Science,Halls,5,2,4,4,4,2,3.0,1.0,12,Doing what I like and being happy
12,UGRD,Foreigner,Malaysia,3,3,Bachelor of Engineering,F,School of Engineering,Residential Colleges,2,2,4,4,6,2,2.0,1.0,13,A good balance of academic and non-academic life
13,UGRD,Foreigner,Hong Kong,4,4,Bachelor of Science (Pharmacy),F,School of Science,Out of Campus,2,1,1,2,5,1,2.0,2.0,14,NaN
14,UGRD,Foreigner,Malaysia,2,2,Bachelor of Engineering,M,School of Engineering,Residences,1,1,1,1,1,3,3.0,1.0,15,An ideal student life is when you have your ti...
16,UGRD,Country Citizen,Singapore,3,3,Bachelor of Business Admin,M,School of Business School,Halls,3,2,2,4,4,2,2.0,2.0,17,A balanced combination between formal learning...
17,UGRD,Foreigner,Indonesia,3,3,Bachelor of Engineering,F,School of Engineering,Residences,1,2,3,2,3,1,2.0,2.0,18,Study-life balance
18,UGRD,Foreigner,Viet Nam,4,4,Bachelor of Engineering,M,School of Engineering,Halls,0,1,3,2,5,2,3.0,2.0,19,NaN
19,UGRD,Foreigner,Viet Nam,1,1,Bachelor of Engineering,M,School of Engineering,Halls,1,0,2,2,2,2,2.0,2.0,20,"""Interact with people and learn new things eve..."
20,UGRD,Foreigner,Viet Nam,2,2,Bachelor of Science (SDE),F,School of Design & Environment,Halls,3,3,3,3,4,2,2.0,2.0,21,One that is not academically pressurising so t...
21,UGRD,Country Citizen,Singapore,2,2,Bachelor of Arts,F,School of Arts & Social Science,Out of Campus,10,1,3,4,3,2,2.0,2.0,22,An ideal student life is one where a student n...
22,UGRD,Permanent Resident,Bangladesh,2,2,Bachelor of Science,F,School of Science,Out of Campus,0,1,4,7,4,2,1.0,2.0,23,full of success and peace
24,UGRD,Permanent Resident,Indonesia,1,1,Bachelor of Arts,F,School of Arts & Social Science,Residences,3,1,2,6,4,2,0.0,2.0,25,Home away from home where you can look up to f...
26,UGRD,Foreigner,Malaysia,4,4,Bachelor of Science,F,School of Science,Halls,3,3,4,3,4,2,2.0,2.0,27,spanned learning blended with fun.
28,UGRD,Country Citizen,Singapore,2,2,Bachelor of Engineering,F,School of Engineering,Out of Campus,3,2,3,3,4,2,2.0,2.0,29,Do not have to worry a lot about grades and en...
30,UGRD,Permanent Resident,Indonesia,3,3,Bachelor of Engineering,F,School of Engineering,Residences,3,3,2,5,4,2,3.0,2.0,31,"not so stressful academically, more colourful ..."
31,UGRD,Foreigner,Malaysia,3,3,Bachelor of Science (Pharmacy),M,School of Science,Halls,3,0,2,3,4,2,2.0,2.0,32,Balance of everything--> answered like never a...
32,UGRD,Foreigner,Malaysia,4,4,Bachelor of Science,F,School of Science,Halls,0,2,3,2,6,1,2.0,2.0,33,Having a lot of chances to know new people and...
33,UGRD,Foreigner,Malaysia,4,4,Bachelor of Science,M,School of Science,Halls,1,3,4,1,2,3,2.0,1.0,34,Being able to excel academically and also deve...
34,UGRD,Country Citizen,Singapore,2,2,Bachelor of Science (Nursing),F,School of Medicine1,Out of Campus,2,1,1,3,2,2,2.0,2.0,35,A student life should involve a lot of learnin...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2913,UGRD,Country Citizen,Singapore,3,3,Bachelor of Engineering,M,School of Engineering,Out of Campus,0,1,3,1,2,2,2.0,2.0,2914,have a great time in University with a job sec...
2914,UGRD,Country Citizen,Singapore,4,4,Bachelor of Social Sciences,M,School of Arts & Social Science,Out of Campus,1,3,2,3,4,2,2.0,2.0,2915,Nothing. I take what I get.
2915,UGRD,Country Citizen,Singapore,3,3,Bachelor of Engineering,M,School of Engineering,Out of Campus,0,2,2,2,6,2,2.0,2.0,2916,doing well in academic and non academic
2916,UGRD,Country Citizen,Singapore,4,4,Bachelor of Business Admin,M,School of Business School,Out of Campus,1,1,1,3,3,2,2.0,2.0,2917,An ideal student life is one where you work ef...
2917,UGRD,Foreigner,Myanmar,3,3,Bachelor of Engineering,F,School of Engineering,Out of Campus,0,1,4,4,4,1,2.0,3.0,2918,"My ideal student life is to be happy, enriched..."
2918,UGRD,Country Citizen,Singapore,2,2,"Bach. of Med.,Bach. of Surg.",F,School of Medicine1,Residences,2,1,5,4,3,2,2.0,2.0,2919,NaN
2919,UGRD,Country Citizen,Singapore,4,4,Bachelor of Business Admin,F,School of Business School,Out of Campus,2,2,1,2,3,3,2.0,1.0,2920,"Having a good balance of both, while being abl..."
2921,UGRD,Foreigner,China,3,3,Bachelor of Science (SDE),F,School of Design & Environment,Out of Campus,2,3,5,4,2,3,2.0,1.0,2922,An ideal student life is a perfect balance of ...
2922,UGRD,Country Citizen,Singapore,4,4,Bachelor of Engineering,M,School of Engineering,Out of Campus,0,0,1,2,1,3,2.0,2.0,2923,Academic-oriented life focusing on EXACT the m...
2923,UGRD,Country Citizen,Singapore,2,2,Bachelor of Arts,F,School of Arts & Social Science,Halls,3,4,4,4,5,2,1.0,2.0,2924,Make friends and enrich self
2924,UGRD,Permanent Resident,China,1,1,Bachelor of Science,F,School of Science,Residential Colleges,3,1,4,1,2,2,2.0,3.0,2925,work life balance
2926,UGRD,Permanent Resident,China,2,2,Bachelor of Engineering,F,School of Engineering,Halls,1,1,2,1,2,2,2.0,2.0,2927,NaN
2927,UGRD,Country Citizen,Singapore,3,3,Bachelor of Science,M,School of Science,Halls,1,3,5,5,1,2,2.0,2.0,2928,fun and engaging and experiential and learn
2928,UGRD,Country Citizen,Singapore,3,3,Bachelor of Engineering,M,School of Engineering,Halls,3,3,4,3,5,2,2.0,2.0,2929,It enriches and makea your university life com...
2929,UGRD,Foreigner,China,4,4,Bachelor of Engineering,M,School of Engineering,Halls,2,1,3,1,1,2,2.0,2.0,2930,NaN
2932,UGRD,Country Citizen,Singapore,3,3,Bachelor of Computing,M,School of Computing,Out of Campus,0,2,2,1,2,2,2.0,3.0,2933,To live with no regrets
2933,UGRD,Country Citizen,Singapore,1,1,Bachelor of Science (SDE),M,School of Design & Environment,Halls,1,2,1,1,1,2,2.0,2.0,2934,a balance between study and fun
2934,UGRD,Country Citizen,Singapore,2,2,Bachelor of Engineering,F,School of Engineering,Halls,0,3,1,1,3,2,2.0,2.0,2935,One where i do well in my studies while partic...
2938,UGRD,Permanent Resident,China,4,4,Bachelor of Science,F,School of Science,Out of Campus,4,2,4,6,4,2,3.0,2.0,2939,"A balanced life of academic pursuit, social in..."
2941,UGRD,Permanent Resident,China,1,1,Bachelor of Arts,F,School of Arts & Social Science,Residential Colleges,0,1,4,5,5,2,NaN,NaN,2942,Enriching and Fun
2942,UGRD,Permanent Resident,China,1,1,Bachelor of Science,F,School of Science,Residential Colleges,1,2,1,2,1,2,NaN,NaN,2943,Interesting and fulfilling
2944,UGRD,Country Citizen,Singapore,4,4,Bachelor of Science (SDE),F,School of Design & Environment,Out of Campus,0,1,3,1,3,2,NaN,NaN,2945,To have a good balance between studying and ha...
2945,UGRD,Country Citizen,Singapore,4,4,Bachelor of Social Sciences,M,School of Arts & Social Science,Out of Campus,2,3,3,4,2,3,NaN,NaN,2946,A good mixture of recreation and studies with ...
2949,UGRD,Country Citizen,Singapore,1,1,Bachelor of Business Admin,M,School of Business School,Residential Colleges,1,3,2,2,4,2,NaN,NaN,2950,"A life that is well managed, with academics th..."
2950,UGRD,Country Citizen,Singapore,1,1,Bachelor of Business Admin,M,School of Business School,Residential Colleges,1,2,6,2,3,2,NaN,NaN,2951,A good balance of both academic and non-academ...
2951,UGRD,Country Citizen,Singapore,2,2,Bachelor of Arts,F,School of Arts & Social Science,Out of Campus,0,1,5,1,4,2,NaN,NaN,2952,good balance of acads and non acads achievements
2952,UGRD,Foreigner,China,1,1,Bachelor of Science (SOC),M,School of Computing,Residential Colleges,1,1,2,2,4,1,NaN,NaN,2953,My ideal student life is a balanced mix of ext...
2953,UGRD,Country Citizen,Singapore,1,1,Bachelor of Science,F,School of Science,Out of Campus,0,1,5,8,3,2,NaN,NaN,2954,The ideal student life is about able to balanc...
2954,UGRD,Country Citizen,Singapore,2,2,"Bach. of Med.,Bach. of Surg.",M,School of Medicine1,Out of Campus,1,1,5,2,1,2,NaN,NaN,2955,Work-life balance with time for leisure activi...
2957,UGRD,Permanent Resident,China,1,1,Bachelor of Science,F,School of Science,Halls,2,2,4,2,3,2,NaN,NaN,2958,My ideal student life is having study-life bal...

In [18]:
DEPARTMENT_INDEX = 7
STRESS_INDEX = 13
SATISFACTION_INDEX = 14

departments = set(dfr.iloc[:, DEPARTMENT_INDEX])
for dep in departments:
    
    dep_rows = dfr[dfr.iloc[:, DEPARTMENT_INDEX] == dep]
    students_count = sum(dep_rows)
    
    stress_col = dep_rows.iloc[:, STRESS_INDEX]  
    stress_avg = stress_col.sum() / students_count
    
    satisfaction_col = dep_rows.iloc[:, SATISFACTION_INDEX]
    satisfaction_avg = satisfaction_col.sum() / students_count

    print "DEP: ", dep, "  STRESS: ", stress_avg, "   SATIS: ", satisfaction_avg

TypeError: unsupported operand type(s) for +: 'int' and 'str'